site_name: supergloo
pages:
- Index: index.md
repo_url: https://github.com/solo-io/supergloo/
site_author: SuperGloo Project Authors
copyright: © Copyright 2018, solo.io Inc.
google_analytics: ['UA-101654320-1', 'supergloo.solo.io']
theme:
  name: 'material'
  favicon: 'img/favicon.ico'
extra_css: [extra.css]
extra:
    version: 0.1.1
