site_name: supergloo
pages:
- Index: index.md
- v1 API reference:
  - Overview: v1/supergloo.solo.io.project.sk.md
  - Encryption: v1/encryption.proto.sk.md
  - Install: v1/install.proto.sk.md
  - Mesh: v1/mesh.proto.sk.md
  - Observability: v1/observability.proto.sk.md
  - Policy: v1/policy.proto.sk.md
  - Routing: v1/routing.proto.sk.md
  - Secrets: v1/secret.proto.sk.md
  - Upstreams: v1/upstream.proto.sk.md
repo_url: https://github.com/solo-io/supergloo/
site_author: SuperGloo Project Authors
copyright: © Copyright 2018, solo.io Inc.
google_analytics: ['UA-101654320-1', 'supergloo.solo.io']
theme:
  name: 'material'
  favicon: 'img/favicon.ico'
extra_css: [extra.css]
extra:
  version: 0.1.1
